steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ai-error-translator/ai-error-translator-backend:latest', './backend']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ai-error-translator/ai-error-translator-backend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'ai-error-translator-backend'
    - '--image'
    - 'gcr.io/ai-error-translator/ai-error-translator-backend:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT_ID=ai-error-translator,API_DEBUG=false,RATE_LIMIT_REQUESTS=100,RATE_LIMIT_WINDOW=3600,ALLOWED_ORIGINS=https://errortranslator.com,ENABLE_METRICS=true,ENABLE_ERROR_TRACKING=true,LOG_LEVEL=INFO,DATABASE_POOL_SIZE=10,DATABASE_MAX_OVERFLOW=20'
    - '--set-secrets'
    - 'GEMINI_API_KEY=gemini-api-key:latest,JWT_SECRET_KEY=jwt-secret-key:latest,API_SECRET_KEY=api-secret-key:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest,SENTRY_DSN=sentry-dsn:latest'

images:
  - 'gcr.io/ai-error-translator/ai-error-translator-backend:latest'